
# parsetab.py
# This file is automatically generated. Do not edit.
_tabversion = '3.8'

_lr_method = 'LALR'

_lr_signature = '620BD02DDD78CBC42602BC40292E9201'
    
_lr_action_items = {'integer':([0,3,4,],[2,2,2,]),'$end':([1,2,5,6,],[0,-3,-1,-2,]),'plus':([1,2,5,6,],[3,-3,3,3,]),'times':([1,2,5,6,],[4,-3,4,4,]),}

_lr_action = {}
for _k, _v in _lr_action_items.items():
   for _x,_y in zip(_v[0],_v[1]):
      if not _x in _lr_action:  _lr_action[_x] = {}
      _lr_action[_x][_k] = _y
del _lr_action_items

_lr_goto_items = {'expr':([0,3,4,],[1,5,6,]),}

_lr_goto = {}
for _k, _v in _lr_goto_items.items():
   for _x, _y in zip(_v[0], _v[1]):
       if not _x in _lr_goto: _lr_goto[_x] = {}
       _lr_goto[_x][_k] = _y
del _lr_goto_items
_lr_productions = [
  ("S' -> expr","S'",1,None,None,None),
  ('expr -> expr plus expr','expr',3,'p_expression_plus','main.py',6),
  ('expr -> expr times expr','expr',3,'p_expression_mult','main.py',10),
  ('expr -> integer','expr',1,'p_expression_id','main.py',14),
]
